Instantiate template call under stylesheet node
The following yang would incorrectly compile the 'gen-foo' template at
the same level as 'module'

module unit-test {
    ...
    grouping ut-group1 {
	call gen-foo($help = "Test foo", $hidden = "internal");
    }
}

template gen-foo ($help, $mandatory) {
  leaf foo {
      help $help;
      if ($mandatory) {
	  mandatory $mandatory;
      }
  }
}

Previously it was instantiated under the 'feature' template, like
this.

stylesheet {
   template "/features" {
       module {
          ...
       }
       template "gen-leaf {}
   }
}

It needed to be at the same level as '/features'

stylesheet {
   template "/features" {
       module {
       }
   }
   template "gen-leaf {}
}

otherwise xsltproc barfs.

  compilation error: file foo.xslt line 49 element template
  element template only allowed as child of stylesheet